version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "local"
      POSTGRES_USER: "local"
      POSTGRES_DB: "login"
    ports:
      - "5432:5432"
