use std::env;

pub struct Environment;
impl Environment {
    pub fn as_string(env_name: &'static str, default: &'static str) -> String {
        env::var(env_name).ok().unwrap_or(default.to_string())
    }
    pub fn as_u16(env_name: &'static str, default: u16) -> u16 {
        env::var(env_name)
            .ok()
            .map(|env| env.parse::<u16>().expect("Failed to parse to u16"))
            .unwrap_or(default)
    }
    pub fn as_u32(env_name: &'static str, default: u32) -> u32 {
        env::var(env_name)
            .ok()
            .map(|env| env.parse::<u32>().expect("Failed to parse to u32"))
            .unwrap_or(default)
    }

    pub fn as_i16(env_name: &'static str, default: i16) -> i16 {
        env::var(env_name)
            .ok()
            .map(|env| env.parse::<i16>().expect("Failed to parse to i16"))
            .unwrap_or(default)
    }

    const JWT_PRIVATE_KEY: &'static str = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNmR2VnlSU1g5RXpRblQ5T2lhNVlqdEYwVEwxcEkrRWNlVHp4bGJZSDIwS3Y3aG9hCnZrTHc2QUVPZWxaSW9uVlFheDhtTndBSDFrQW5iZG5ZdEVOc3pkclNHNHlYZndjMkxWbTVkMmpMcnFPZjhiSEcKdk9TSDVEVDZwL3MyQXgwdmRuZWI4UFpTUHVONHZOZ3FscjRtUWV2UGEvM2pXcXNCbXdCbDFiODN4MVhaeUFqSAo0NUU2b3l1RWc1d21JYnY4R3NFZ0huSkliMFRFUDBabEE5dmJFN3BRTm02WTIrY3hrbTFrWFlIUGR1Nk9hV01OCndCZlFrT1JJWTJraURDRlU5VENRVzhFVmNyR1BaTnRCa05WOWxpcHVvZms0Y1FyaTVRQ2Z4Mlp3V1cyd3o0cXQKb3RLT0NCY0RaTFI1UVFMeG5XSnQ4eGoxVWRIRU9ySFZxYkxPbFFJREFRQUJBb0lCQUFubmFRRG9rZHpqU2V4Mgo2MlVTVUtiUHdReWs4dWgxbHFhZHlaOXRBNTBxRUZoVm02OVdGMnpENnJDTXFldlRheEgyVWtCL0RGWHJCcUIwCjJ1UWJmT2FrNzBRQ2FzSVM5SnpzRVZvNHduT0ZjM2NoYjhpOUp2SW51anZWL0Q0YWhOR1FGRGNhdjNYeFhVSW0KSjN1VjF2bnd1aXFaS0lGRS83N29QK2ZTL3RJK3dFMTAweDhDaWdtZ2k1M2QrNmNuSXQrdUtBaVhwS0xZRlhIcgpXQlM0M2Q3K2hYaGJISE9CRGhSMkNDYkFBSndsSVNHRDRMUVB5b1pqaDRZbitXTTZlS3prN3JIdzFHczkyemowCkVNQ25lTHQwVmw5aDlCOWJMQ1JSTXJjNjZBTEY3YWY4OGk5MFN1WTE2T2tUNVhDQkFxM3hmbTNkOHB1eXJrN3YKS2lDMWZLRUNnWUVBK1VLenFyK0JpRWI4NlRXM0NnL3lMQW81dVdHbm5LdVV1NTU0eGJRWVgyeFBROEtUakVvOApzTUJYMDArUE5kR1N6VHcvditCSmF6NzF3L1o5eUxpVzdrZXkxUkh5T0N5SE83dUlGK3loMzlNQTZDRW56OUVNCnljeC9SVVhlbUJEM2Q5dEdIbG5STDFSd2RxMlBWTGNDb3dDTjR5MGRxQjVnN29tRktHWUtlS1VDZ1lFQThDNkcKNmZjZ3RiWWFxVWs2VldHalFYdzJFMno5MXpWazFjS0k2Q0FnOUlxbWl6M2o2K2d1dHhtT2VpZHZ4dCs0cytHTQp6VFlNREJ5UmdYVHhxYnl6eHhPS09LWHkvTS9rMUovWUdmRHJ4bkh4TzBQR0o4MEZ3UGN0UnhqVStrMHI0eGNyCmFOVUZaVXZiWTdmREw5amVCazNjVFRnSzJIYWJsZHE2cXZoV0t6RUNnWUEvUXQrSWtXd1ZvemFqRlovcjdOb2cKdFVPck9nNnBJNTd1OHl4aHVQQ0tuMW1Lc0FKMGs0N05xVE5oRFFzaXRKcldmZGtNSUtkaGthd2NYUjNWYUl2ZAowOUtlWXh5Zmh5V1hVbVFhOWxLckZNbGhJTEVTL0ZLTGtOd29QN0JiMWNxSTM5enU3UXE3UVduOXBOVUF3aVhvCktzYllCbVpGZWRoT0VoYjZodE5YaFFLQmdCNWZ3L0FTc0xCS04xVHhUYzgrYWNiK1RsaG1rRE9ITFJsYllMVDYKV3pDUjJENER0YTgvemFpYU1zcC84a0xVU0NkM2ZyYjAvdEVKUzkxelRKeUtvTEdzWnU2RERoZXFzdVd3MFVOMgpsRnFrVGoyUWRKN1Q3c1pZZkFGaHdvMWs5UWZqQmpwYnRqTDVST1YzZDllMU5WN1d1ZVdLRU5VUEt0M29xM0t6CnRUSUJBb0dBWFYyVXplRWd2WmVVd1R0dmFDNll2UXZpVzJSbzhDdG1vRVRIK2QvdHJlaG94V2htcFJQK05iakkKWmFNdmthV1EzNUJlakJEend5SEluVk52cnBiZ0NhekxYTXhhaTREeXVhMk4rR1I2a3BHUlE4YXp2US9XWEt3RwpTR24ya3JkK1pNVGxUUitiRnF0WWE0MnNoUHFhYUNJVTQ3Yk5VaUxvU0Nkc2xSeEN0TG89Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==";
    const JWT_PUBLIC_KEY: &'static str = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE2ZHZWeVJTWDlFelFuVDlPaWE1WQpqdEYwVEwxcEkrRWNlVHp4bGJZSDIwS3Y3aG9hdmtMdzZBRU9lbFpJb25WUWF4OG1Od0FIMWtBbmJkbll0RU5zCnpkclNHNHlYZndjMkxWbTVkMmpMcnFPZjhiSEd2T1NINURUNnAvczJBeDB2ZG5lYjhQWlNQdU40dk5ncWxyNG0KUWV2UGEvM2pXcXNCbXdCbDFiODN4MVhaeUFqSDQ1RTZveXVFZzV3bUlidjhHc0VnSG5KSWIwVEVQMFpsQTl2YgpFN3BRTm02WTIrY3hrbTFrWFlIUGR1Nk9hV01Od0JmUWtPUklZMmtpRENGVTlUQ1FXOEVWY3JHUFpOdEJrTlY5CmxpcHVvZms0Y1FyaTVRQ2Z4Mlp3V1cyd3o0cXRvdEtPQ0JjRFpMUjVRUUx4bldKdDh4ajFVZEhFT3JIVnFiTE8KbFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==";
    
    pub fn jwt_public_key() -> String {
        Self::as_string("BASE64_JWT_PUBLIC_KEY", Self::JWT_PUBLIC_KEY)
    }
    
    pub fn jwt_private_key() -> String {
        Self::as_string("BASE64_JWT_PRIVATE_KEY", Self::JWT_PRIVATE_KEY)
    }
}
